name: Java CI

on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: debian:8

    steps:

      - name: Install dependencies (g++, openjdk, maven, git)
        run: |
          apt-get update
          apt-get install build-essential openjdk-7-jre openjdk-7-jdk maven git -y
      - name: Checkout repository and submodules and build
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          git checkout -b $GITHUB_REF_NAME
          export GITHUB_REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY  | awk '{split($0,a,"/"); print a[2]}')
          cd $GITHUB_REPOSITORY_NAME
          git submodule update --init --recursive
          mvn --batch-mode --update-snapshots "-Djar.finalName=jfasttext-linux" package
          mkdir /staging
          cp target/jfasttext-linux.jar /staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package Linux
          path: /staging
  
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven Windows
        run: mvn --batch-mode --update-snapshots "-Djar.finalName=jfasttext-windows" package 
      - run: mkdir staging && cp target/jfasttext-windows.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package Windows
          path: staging

  build_macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      
      - name: Build with Maven MacOS
        run: mvn --batch-mode --update-snapshots "-Djar.finalName=jfasttext-macos" package
      - run: mkdir staging && cp target/jfasttext-macos.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package MacOS
          path: staging
  