name: Java CI

on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: debian:8

    steps:

      - name: Install dependencies (g++, openjdk, maven, git)
        run: |
          apt-get update
          apt-get install build-essential openjdk-7-jre openjdk-7-jdk maven git -y
      - name: Checkout repository and submodules
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY
          export GITHUB_REPOSITORY_NAME=$(echo $GITHUB_REPOSITORY  | awk '{split($0,a,"/"); print a[2]}')
          cd $GITHUB_REPOSITORY_NAME
          git submodule update --init --recursive
      - name: Build with Maven Linux
        run: |
          ls -a
          cat pom.xml
          mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp target/*jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package Linux
          path: staging
  
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven Windows
        run: mvn --batch-mode --update-snapshots package 
      - run: mkdir staging && cp target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package Windows
          path: staging