name: Java CI

on: [push]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: debian:8

    steps:

      - name: Install dependencies (g++, openjdk, maven, git)
        run: |
          apt-get update
          apt-get install build-essential openjdk-7-jre openjdk-7-jdk maven git -y
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodule fasttext
        run: git submodule update --init --recursive
      - name: Build with Maven Linux
        run: mvn --batch-mode --update-snapshots package -Djar.finalName=jfasttext-linux
      - run: mkdir staging && cp target/jfasttext-linux.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package Linux
          path: staging
  
  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven Windows
        run: mvn --batch-mode --update-snapshots package -Djar.finalName=jfasttext-windows
      - run: mkdir staging && cp target/jfasttext-windows.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package Windows
          path: staging